[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn BMI_calculator.wsgi:application"
