# Generated by Django 4.2 on 2025-07-01 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(max_length=10)),
                ('activity_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi_category', models.CharField(max_length=20)),
                ('bmr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tdee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ibw', models.CharField(max_length=50)),
                ('mhr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latest_metrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_latest_metrics', to='my_App.healthmetrics'),
        ),
    ]
